[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]   

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

#forge script script/GridlyLeaderboard.s.sol:GridlyLeaderboardScript \
#  --rpc-url $RPC_URL \
#  --broadcast